### ISSUE TITLE
About the license for this model

### ISSUE THREAD

**Issue by PINTO0309** [rafaeelaudibert/FINNger#1]
Thank you for sharing your great code. :smiley_cat:

What is the license for this model? I'd like to cite it to the repository I'm working on if possible, but I want to post the license correctly.
https://github.com/PINTO0309/PINTO_model_zoo

Thank you.

**Comment by rafaeelaudibert** [comment]
Hey @PINTO0309,

Thank **you** for taking a look at it :). Happy to be able to help with your work.

I've just added a new commit with an MIT [LICENSE](./LICENSE) file.
Thanks for your interest :)

**Comment by PINTO0309** [comment]
Thanks!
